const animals=[
{id:'african-elephant',name:'African Elephant',scientific:'Loxodonta africana',group:'Mammals',emoji:'🐘',color:'#dceff2',habitat:'Savanna, woodland and forest',region:'Sub-Saharan Africa',diet:'Herbivore',status:'Endangered',lifespan:'60–70 years',description:'The largest land animal on Earth, African elephants use their trunks to breathe, smell, touch and gather food.',facts:['Elephants communicate using sounds that can travel through the ground.','Their large ears help them lose heat.'],featured:1},
{id:'bengal-tiger',name:'Bengal Tiger',scientific:'Panthera tigris tigris',group:'Mammals',emoji:'🐯',color:'#fff0d0',habitat:'Grasslands, forests and mangroves',region:'The Indian subcontinent',diet:'Carnivore',status:'Endangered',lifespan:'10–15 years',description:'A powerful solitary cat and excellent swimmer, the Bengal tiger is identified by its bold striped coat.',facts:['No two tigers have exactly the same stripe pattern.','Tigers are strong swimmers and may cross wide rivers.'],featured:2},
{id:'blue-whale',name:'Blue Whale',scientific:'Balaenoptera musculus',group:'Mammals',emoji:'🐋',color:'#dce8ff',habitat:'Open ocean',region:'Oceans worldwide',diet:'Filter feeder',status:'Endangered',lifespan:'70–90 years',description:'Blue whales are the largest animals known to have ever lived. They filter tiny krill from seawater.',facts:['A blue whale heart can weigh as much as a small car.','Their calls can travel hundreds of kilometres underwater.'],featured:3},
{id:'emperor-penguin',name:'Emperor Penguin',scientific:'Aptenodytes forsteri',group:'Birds',emoji:'🐧',color:'#e6f3f7',habitat:'Antarctic sea ice',region:'Antarctica',diet:'Carnivore',status:'Near Threatened',lifespan:'15–20 years',description:'The tallest penguin species, emperor penguins survive Antarctic winters by huddling together for warmth.',facts:['Males balance a single egg on their feet during incubation.','They can dive deeper than 500 metres.'],featured:4},
{id:'green-sea-turtle',name:'Green Sea Turtle',scientific:'Chelonia mydas',group:'Reptiles',emoji:'🐢',color:'#e6f5d9',habitat:'Tropical and subtropical seas',region:'Warm oceans worldwide',diet:'Mostly herbivore',status:'Endangered',lifespan:'70–80 years',description:'Green sea turtles are long-distance ocean travellers. Adults often graze on seagrass and algae.',facts:['They navigate using Earth’s magnetic field.','Females return to nesting beaches, often near where they hatched.'],featured:5},
{id:'red-panda',name:'Red Panda',scientific:'Ailurus fulgens',group:'Mammals',emoji:'🦊',color:'#ffe8d7',habitat:'Temperate mountain forests',region:'Eastern Himalayas',diet:'Omnivore',status:'Endangered',lifespan:'8–10 years',description:'Red pandas are tree-dwelling mammals with a flexible ankle that helps them climb head-first down trunks.',facts:['Their name reflects their reddish coat, not a close relationship to giant pandas.','Bamboo makes up much of their diet.'],featured:6},
{id:'green-anaconda',name:'Green Anaconda',scientific:'Eunectes murinus',group:'Reptiles',emoji:'🐍',color:'#e0f0db',habitat:'Swamps, marshes and slow rivers',region:'Tropical South America',diet:'Carnivore',status:'Least Concern',lifespan:'10–12 years',description:'The green anaconda is a heavy-bodied constrictor that spends much of its life in and around water.',facts:['Females are considerably larger than males.','They can remain underwater for several minutes.'],featured:7},
{id:'clownfish',name:'Clownfish',scientific:'Amphiprioninae',group:'Fish',emoji:'🐠',color:'#fff0cf',habitat:'Coral reefs and lagoons',region:'Indian and Pacific Oceans',diet:'Omnivore',status:'Least Concern',lifespan:'6–10 years',description:'Clownfish live among the stinging tentacles of sea anemones, forming one of nature’s famous partnerships.',facts:['A mucus layer protects them from their host anemone’s sting.','The largest fish in a group is the breeding female.'],featured:8},
{id:'monarch-butterfly',name:'Monarch Butterfly',scientific:'Danaus plexippus',group:'Invertebrates',emoji:'🦋',color:'#fff0d8',habitat:'Meadows, fields and woodland edges',region:'The Americas',diet:'Herbivore',status:'Endangered',lifespan:'2–6 weeks (migratory generations longer)',description:'Monarch butterflies are famous for a multi-generation migration and their orange-and-black warning colours.',facts:['Caterpillars feed on milkweed.','Some migrations cover thousands of kilometres.'],featured:9},
{id:'snowy-owl',name:'Snowy Owl',scientific:'Bubo scandiacus',group:'Birds',emoji:'🦉',color:'#edf5f6',habitat:'Arctic tundra and open fields',region:'Arctic regions',diet:'Carnivore',status:'Vulnerable',lifespan:'10 years in the wild',description:'Snowy owls are Arctic hunters with excellent hearing and feathers that extend down their legs.',facts:['Females usually have more dark markings than males.','They may hunt during daylight in the Arctic summer.'],featured:10},
{id:'komodo-dragon',name:'Komodo Dragon',scientific:'Varanus komodoensis',group:'Reptiles',emoji:'🦎',color:'#e5eddc',habitat:'Tropical dry forest and savanna',region:'A few Indonesian islands',diet:'Carnivore',status:'Endangered',lifespan:'Up to 30 years',description:'The Komodo dragon is the world’s largest living lizard, using a strong sense of smell to locate prey.',facts:['They can detect carrion from several kilometres away.','Young dragons spend time in trees to avoid predators.'],featured:11},
{id:'giant-panda',name:'Giant Panda',scientific:'Ailuropoda melanoleuca',group:'Mammals',emoji:'🐼',color:'#edf1f2',habitat:'Mountain bamboo forests',region:'Central China',diet:'Herbivore',status:'Vulnerable',lifespan:'15–20 years',description:'Giant pandas have a specialised wrist bone that works like a thumb for gripping bamboo.',facts:['They spend many hours each day eating bamboo.','Pandas are bears, despite their unusual diet.'],featured:12}
];
const groups=[['Mammals','🐾','4 guides'],['Birds','🪶','2 guides'],['Reptiles','🦎','3 guides'],['Fish','🐟','1 guide'],['Invertebrates','🦋','1 guide'],['Amphibians','🐸','Coming soon']];
let currentGroup='All',query='';const grid=document.querySelector('#animalGrid');const allGrid=document.querySelector('.all-grid');
function card(a){return `<article class="animal-card" tabindex="0" data-id="${a.id}"><div class="card-image" style="background:${a.color}"><small>${a.group}</small>${a.emoji}</div><div class="card-info"><h3>${a.name}</h3><p>${a.scientific}</p><div class="card-meta"><span class="tag">${a.habitat.split(',')[0]}</span><span class="tag">${a.status}</span></div></div></article>`}
function attachCards(){document.querySelectorAll('.animal-card').forEach(c=>{c.addEventListener('click',()=>openAnimal(c.dataset.id));c.addEventListener('keydown',e=>{if(e.key==='Enter')openAnimal(c.dataset.id)})})}
function render(){let list=animals.filter(a=>currentGroup==='All'||a.group===currentGroup).filter(a=>Object.values(a).join(' ').toLowerCase().includes(query.toLowerCase()));const sort=document.querySelector('#sortSelect').value;if(sort==='name')list.sort((a,b)=>a.name.localeCompare(b.name));if(sort==='lifespan')list.sort((a,b)=>parseInt(b.lifespan)-parseInt(a.lifespan));if(sort==='featured')list.sort((a,b)=>a.featured-b.featured);grid.innerHTML=list.slice(0,4).map(card).join('');allGrid.innerHTML=list.map(card).join('');document.querySelector('#emptyState').hidden=list.length>0;attachCards()}
function openAnimal(id){const a=animals.find(x=>x.id===id);document.querySelector('#dialogContent').innerHTML=`<div class="dialog-cover" style="background:${a.color}">${a.emoji}</div><div class="dialog-body"><p class="eyebrow">${a.group} · ${a.status}</p><h2>${a.name}</h2><p class="scientific">${a.scientific}</p><p>${a.description}</p><div class="detail-grid"><div class="detail"><b>Habitat</b><span>${a.habitat}</span></div><div class="detail"><b>Range</b><span>${a.region}</span></div><div class="detail"><b>Diet</b><span>${a.diet}</span></div><div class="detail"><b>Lifespan</b><span>${a.lifespan}</span></div></div><h3>Interesting facts</h3><ul class="facts">${a.facts.map(f=>`<li>${f}</li>`).join('')}</ul></div>`;document.querySelector('#animalDialog').showModal()}
function doSearch(value){query=value.trim();document.querySelector('#heroSearchInput').value=value;document.querySelector('#explore').scrollIntoView({behavior:'smooth'});render()}
document.querySelector('#heroSearch').addEventListener('submit',e=>{e.preventDefault();doSearch(document.querySelector('#heroSearchInput').value)});document.querySelectorAll('[data-search]').forEach(b=>b.addEventListener('click',()=>doSearch(b.dataset.search)));document.querySelector('#groupFilters').addEventListener('click',e=>{if(!e.target.dataset.group)return;currentGroup=e.target.dataset.group;query='';document.querySelector('#heroSearchInput').value='';document.querySelectorAll('#groupFilters button').forEach(b=>b.classList.toggle('active',b===e.target));render()});document.querySelector('#sortSelect').addEventListener('change',render);document.querySelector('#groupGrid').innerHTML=groups.map(g=>`<button class="group-card" data-group-card="${g[0]}"><span>${g[1]}</span><strong>${g[0]}</strong><small>${g[2]}</small></button>`).join('');document.querySelectorAll('[data-group-card]').forEach(b=>b.addEventListener('click',()=>{const group=b.dataset.groupCard;if(group==='Amphibians')return;currentGroup=group;document.querySelectorAll('#groupFilters button').forEach(x=>x.classList.toggle('active',x.dataset.group===group));document.querySelector('#explore').scrollIntoView({behavior:'smooth'});render()}));
const animalDialog=document.querySelector('#animalDialog');document.querySelector('#closeDialog').addEventListener('click',()=>animalDialog.close());const aniDialog=document.querySelector('#aniDialog');function showAni(){aniDialog.showModal();document.querySelector('#aniQuestion').focus()}document.querySelector('#openAni').addEventListener('click',showAni);document.querySelector('#openAni2').addEventListener('click',showAni);document.querySelector('#closeAni').addEventListener('click',()=>aniDialog.close());document.querySelectorAll('[data-question]').forEach(b=>b.addEventListener('click',()=>{document.querySelector('#aniQuestion').value=b.dataset.question}));document.querySelector('#aniForm').addEventListener('submit',e=>{e.preventDefault();const val=document.querySelector('#aniQuestion').value.trim();if(!val)return;document.querySelector('#aniResponse').hidden=false;document.querySelector('#aniResponse').innerHTML=`<strong>ANI is still growing.</strong><br>This question will be answered from ANIMOPEDIA's structured database once the ANI integration is connected. You can explore the guides below in the meantime.`});
const sidePanel=document.querySelector('#sidePanel');document.querySelector('#openMenu').addEventListener('click',()=>sidePanel.classList.add('open'));document.querySelector('#closeMenu').addEventListener('click',()=>sidePanel.classList.remove('open'));document.querySelectorAll('.side-nav a').forEach(a=>a.addEventListener('click',()=>sidePanel.classList.remove('open')));render();
