/* ANIMOPEDIA experience layer: learning modes, Read Aloud, and the Evolution Museum guide. */
(() => {
  const gate = document.querySelector('#ageGate');
  const owl = document.querySelector('#owlGuide');
  const owlMessage = document.querySelector('#owlMessage');
  const modes = {kids:'Young Explorer', explorer:'Explorer', student:'Student', general:'General Explorer'};
  let mode = localStorage.getItem('animopedia-mode');
  const announce = text => { let live=document.querySelector('#speechStatus'); if(!live){live=document.createElement('div');live.id='speechStatus';live.className='sr-only';document.body.appendChild(live)} live.textContent=text; };
  function setMode(value, firstRun=false){
    mode=value; localStorage.setItem('animopedia-mode',value); document.body.classList.remove('kids-mode','mode-explorer','mode-student','mode-general'); document.body.classList.add(`mode-${value}`);
    if(value==='kids'){owl.hidden=false;owlMessage.textContent='Whooo wants to explore an animal today? I will help explain tricky words.'}else owl.hidden=true;
    gate.classList.add('hidden');setTimeout(()=>gate.hidden=true,350);if(!firstRun)announce(`Learning style changed to ${modes[value]}.`);
  }
  document.querySelectorAll('[data-mode]').forEach(b=>b.addEventListener('click',()=>setMode(b.dataset.mode)));
  document.querySelector('#settingsButton')?.addEventListener('click',()=>{gate.hidden=false;requestAnimationFrame(()=>gate.classList.remove('hidden'))});
  if(mode&&modes[mode])setMode(mode,true);else gate.hidden=false;

  let currentButton=null;
  function speak(text,button){
    if(!('speechSynthesis' in window)){announce('Read Aloud is not supported by this browser.');return}
    if(speechSynthesis.speaking&&currentButton===button){speechSynthesis.cancel();button.classList.remove('speaking');button.textContent='🔊 Read aloud';currentButton=null;return}
    speechSynthesis.cancel();document.querySelectorAll('.speaking').forEach(x=>{x.classList.remove('speaking');x.textContent='🔊 Read aloud'});
    const utterance=new SpeechSynthesisUtterance(text);utterance.rate=mode==='kids'?.88:.98;currentButton=button;button.classList.add('speaking');button.textContent='⏹ Stop reading';
    utterance.onend=()=>{button.classList.remove('speaking');button.textContent='🔊 Read aloud';currentButton=null};speechSynthesis.speak(utterance);
  }
  document.querySelectorAll('[data-read-target]').forEach(b=>b.addEventListener('click',()=>{const t=document.getElementById(b.dataset.readTarget);speak(t?.textContent||'',b)}));
  document.querySelector('#owlRead')?.addEventListener('click',()=>speak(owlMessage.textContent,document.querySelector('#owlRead')));
  const dialogContent=document.querySelector('#dialogContent');
  new MutationObserver(()=>{if(dialogContent&&!dialogContent.querySelector('.read-aloud')&&dialogContent.textContent.trim()){const b=document.createElement('button');b.className='read-aloud';b.textContent='🔊 Read aloud';b.type='button';b.onclick=()=>speak(dialogContent.innerText,b);dialogContent.querySelector('.dialog-body')?.prepend(b)}}).observe(dialogContent,{childList:true,subtree:true});

  /* The museum is intentionally stored as chapters so visitors can read, jump, or listen without one giant wall of text. */
  const chapters=[
    ['Entrance: A question written in stone','Welcome to the Evolution Museum. Before we begin, pause at the entrance and look at the stone beneath your feet. It may seem ordinary, but it is part of a planet with a deep and changing history. Earth is about 4.54 billion years old. Life has existed for a large part of that time, although the earliest life was very different from the animals we know today. There were no forests, birds, elephants, or people. There were oceans, minerals, energy, and tiny living cells. Over immense spans of time, living populations changed. Some changes helped organisms survive in particular environments. Some did not. Some lineages disappeared completely. Evolution is not a ladder with one species at the top. It is more like a branching family tree, with many branches growing, splitting, and sometimes ending.\n\nThis museum uses a simplified tour to introduce evidence from fossils, anatomy, genetics, embryology, and the distribution of organisms. A simplified explanation is useful, but it is still an explanation. Scientists continue to test details, debate interpretations, and revise ideas when new evidence appears. That is a strength of science, not a weakness. As you walk through the exhibits, remember three words: variation, inheritance, and time. Differences occur among living things. Some differences can be inherited. Across many generations, those differences can influence which organisms leave descendants. The result is the extraordinary diversity of life around us.'],
    ['Exhibit I: The first living systems','The earliest chapter of life is hidden mostly in microscopic evidence. The first organisms were single cells, and their bodies did not leave large bones or shells behind. Even so, rocks can preserve chemical clues and structures made by ancient communities. Some of the oldest evidence associated with life comes from very ancient rocks, although scientists carefully examine whether a structure could have formed without biology.\n\nEarly cells lived in oceans and used the materials and energy available around them. Over time, some cells evolved ways to capture light energy. Photosynthetic organisms changed their surroundings by releasing oxygen. Oxygen became important for complex life, but it was also harmful to many organisms that had evolved without it. This is a recurring theme in evolution: a change can create opportunities for some lineages while making life harder for others.\n\nMuch later, cells with internal compartments and genetic material enclosed in a nucleus appeared. Complex cells may have gained some of their structures through endosymbiosis, in which one cell lived inside another and the partnership eventually became permanent. Mitochondria, the energy-producing structures in animal cells, and chloroplasts in plants have features that support this history. The museum does not show this transition as a single magical moment. It was a long evolutionary process involving populations, relationships, and changes accumulated over time.'],
    ['Exhibit II: Bodies become diverse','Around 600 to 500 million years ago, animal diversity increased dramatically in the fossil record. This interval is often associated with the Cambrian diversification. It was not the first appearance of all animal life, and it was not a single week in which every modern group suddenly appeared. Rather, fossils from this interval show many new body forms, hard parts, feeding strategies, and ecological relationships.\n\nA body is a set of solutions to environmental problems. A shell can protect a soft body. Jointed limbs can help an animal walk, swim, or capture food. Eyes can detect light, and muscles can create movement. Evolution does not design from a blank page. It modifies inherited structures. That is why the limbs of a bat, a whale, a horse, and a human share underlying bones even though they perform different jobs.\n\nFossils are not photographs of every generation. Fossilisation is rare, and soft bodies usually disappear. The record is therefore incomplete and uneven. Yet fossils can still reveal the order in which features appeared, the environments animals occupied, and the ways bodies changed. Scientists combine fossil evidence with living anatomy and genetic data to build and test evolutionary relationships.'],
    ['Exhibit III: The move onto land','Life began in water, but some lineages eventually made use of land. Plants established themselves on land before vertebrate animals became fully terrestrial. For animals, the move required solutions to several problems: preventing water loss, supporting the body against gravity, breathing air, moving across uneven surfaces, and reproducing in an environment where eggs and young could dry out.\n\nLobed-finned fishes already had bones and muscles that could support their fins. In some lineages, changes accumulated in the skeleton and respiratory system. Fossils such as Tiktaalik help illustrate a stage with both fish-like and tetrapod-like features, although evolution was not a straight march toward modern four-limbed animals. Many early branches experimented with different body plans, and most eventually disappeared.\n\nThe first tetrapods were not simply “fish becoming lizards.” They were diverse animals living in changing wetlands. Later groups evolved stronger limbs, improved air-breathing, and new reproductive strategies. Amphibians still show a close connection to water in many parts of their life cycles. Amniotes, the broader group containing reptiles, birds, and mammals, evolved membranes around their embryos that helped reproduction occur away from open water. This innovation opened new habitats and changed the future of vertebrate life.'],
    ['Exhibit IV: Reptiles, birds, and the dinosaur halls','Dinosaurs lived for more than 160 million years and included a remarkable range of sizes, shapes, diets, and behaviours. The word dinosaur refers to a particular branch of reptiles, not every prehistoric reptile. Pterosaurs were flying reptiles, but they were not dinosaurs. Marine reptiles such as ichthyosaurs and plesiosaurs also lived alongside dinosaurs but belonged to different branches. Careful classification matters because the past was more diverse than a single “age of monsters” label suggests.\n\nEvidence shows that many dinosaurs had feathers or feather-like coverings. Birds are living dinosaurs, specifically members of the theropod branch. The connection is supported by fossils, skeletal anatomy, nesting evidence, and other lines of research. Modern birds are not unchanged dinosaurs; they are descendants of one dinosaur lineage that survived major changes in Earth’s history.\n\nA large asteroid impact about 66 million years ago contributed to a mass extinction at the end of the Cretaceous Period. It was not the only environmental change, and scientists study multiple causes and effects. Non-avian dinosaurs disappeared, while birds and many other organisms survived. Mammals, insects, plants, reptiles, and marine life also changed after the event. Extinction closes branches, but survivors may later diversify into newly available ecological roles.'],
    ['Exhibit V: The rise of mammals','Mammals did not suddenly appear after the dinosaurs vanished. Their ancestors lived alongside dinosaurs for millions of years. Early mammals were often small, but they were diverse and occupied different habitats. Mammals share features such as hair, milk production, and three tiny middle-ear bones. These traits were modified in many directions as different lineages evolved.\n\nAfter the end-Cretaceous extinction, surviving mammals diversified. Some became large herbivores, some became ocean swimmers, some evolved powered flight, and others became specialised predators or burrowers. Whales retain evidence of their land-mammal ancestry in their skeletons and development. Bats evolved powered flight independently from birds, using a different wing structure. Primates evolved grasping hands and forward-facing eyes in a history shaped by forests, movement, diet, and social life.\n\nEvolution does not guarantee progress toward complexity or intelligence. A tiny animal can be extraordinarily well adapted to its environment. A simple body can persist for millions of years if it works. Mammal history is a gallery of trade-offs: warm bodies require energy, large brains require food, and specialised limbs may help in one habitat while limiting options in another.'],
    ['Exhibit VI: Extinction and renewal','Extinction is the permanent disappearance of a species. It is a normal part of Earth’s history, but the rate and causes of extinction vary. Mass extinctions are intervals when many groups disappear in a relatively short geological period. Scientists recognise several major mass extinction events, including the end-Permian event, which was especially severe, and the end-Cretaceous event associated with the asteroid impact.\n\nExtinction can be caused by rapid environmental change, volcanic activity, sea-level shifts, climate change, habitat loss, new predators, disease, competition, or combinations of factors. In modern ecosystems, human activities have greatly increased pressure on many species through land conversion, overharvesting, pollution, invasive species, and climate change. Conservation science uses evidence to reduce those pressures and protect populations.\n\nRecovery after a mass extinction can take millions of years. Empty ecological roles may eventually be filled, but the original species and relationships cannot simply be restored. This is why conservation is not only about saving attractive animals. It is about protecting habitats, genetic diversity, ecological interactions, and the processes that allow life to continue changing.'],
    ['Exhibit VII: How scientists know','The museum’s specimens are not guesses arranged for decoration. They represent evidence interpreted through scientific methods. Fossils show ancient structures and sometimes preserve tracks, nests, stomach contents, feathers, or skin impressions. Comparative anatomy identifies shared structures and functional differences. Homologous bones can indicate common ancestry even when their present uses differ. Analogous features can evolve independently when unrelated organisms face similar environmental challenges.\n\nDNA provides another powerful source of evidence. Species with more similar genetic sequences often share a more recent common ancestor, although scientists must account for gene duplication, hybridisation, incomplete lineage sorting, and other complications. A family tree is a scientific model supported by data; it is not a literal drawing found in nature. Different datasets can produce competing trees, and researchers compare them carefully.\n\nBiogeography also matters. Unique species on islands, related fossils on continents now separated, and the distribution of marsupials are easier to understand when continents move and populations split. Evolutionary developmental biology examines how changes in development can alter bodies. No single clue explains all life. Confidence becomes stronger when independent lines of evidence point toward the same history.'],
    ['Exhibit VIII: Adaptation is a relationship','An adaptation is an inherited trait that increases reproductive success in a particular environment, across generations. It is not simply anything useful, and an individual cannot evolve a new inherited trait because it needs one. Individuals can learn, grow, acclimatise, or change behaviour during their lives. Evolution changes populations over generations.\n\nConsider the snowshoe hare’s seasonal coat, a camel’s ability to cope with desert conditions, or a penguin’s dense feathers and body shape for cold water. Each feature has costs and benefits. A thick coat can retain heat but may be too warm in another season. A large beak can process a certain food but require energy to build. Natural selection acts on variation in real environments, where conditions change and resources are limited.\n\nAnimals also interact with other organisms. Flowering plants and pollinators influence one another. Predators and prey can shape speed, camouflage, warning colours, and behaviour. Parasites can drive immune adaptations. These relationships do not produce perfect organisms. They produce organisms with histories, compromises, and limits. Understanding those limits helps us explain why a species may be vulnerable when its environment changes quickly.'],
    ['Exhibit IX: One living family tree','Look around the final gallery. A whale, a bat, a tiger, a penguin, a turtle, and a butterfly may appear extremely different, but each belongs to a lineage with a history of descent and change. “Related” does not mean identical. It means that two organisms share ancestors at some point in the past. The more recent the shared ancestor, the closer the relationship represented on a particular tree.\n\nHumans are part of this story, not separate from it. Humans share ancestry with other primates, and more distant ancestry with all living animals. This does not reduce human uniqueness. It places our abilities, cultures, and responsibilities in a scientific context. We are one young branch in a very old tree, dependent on other branches and on the ecosystems that sustain us.\n\nThe living world is not a catalogue of finished products. It is an ongoing process. Populations continue to change. New mutations arise, genes move between populations, organisms migrate, and environments shift. Evolution has no final destination. The species alive today are survivors of previous histories, and the choices humans make can influence which lineages continue into the future.'],
    ['Exit Hall: Carry the question with you','Our tour ends, but the museum’s central question travels outside with you: how did this living thing come to be the way it is? Ask it when you see a bird’s wing, a beetle’s shell, a tree’s seed, or the shape of a whale’s flipper. Look for evidence. Separate what is directly observed from what is inferred. Be comfortable saying “we do not know yet.” That sentence is not an ending; it is an invitation to investigate.\n\nEvolutionary science helps explain biodiversity, but it also helps us make practical decisions. It informs conservation plans, disease research, agriculture, ecology, and the protection of genetic diversity. A species is not merely a name on a list. It is a population with relationships, behaviours, and a place in a changing system.\n\nThank you for visiting the Evolution Museum. You can return to the bright galleries of ANIMOPEDIA, open an animal guide, compare two species, or choose a new branch of the tree. The history of life is too large for one visit and too interesting to finish. Keep asking careful questions. Keep learning from evidence. And remember: every animal you meet is carrying a piece of deep time.']
  ];
  const room=document.querySelector('#museum-timeline');
  if(room){
    room.innerHTML=`<div class="museum-room-heading"><p class="museum-label">Full audio guide · ${chapters.length} chapters</p><h2>A very long story</h2><p>Walk through the history of life one chapter at a time. The guide is an educational introduction, not a replacement for specialist sources.</p><div class="museum-controls"><button id="museumRead">🔊 Read full tour</button><button id="museumStop">■ Stop</button><span id="museumStatus" role="status">Ready when you are.</span></div></div><div class="museum-chapters">${chapters.map((c,i)=>`<article class="museum-chapter" id="chapter-${i+1}"><div class="chapter-number">${String(i+1).padStart(2,'0')}</div><div><p class="chapter-time">Exhibition ${i+1}</p><h3>${c[0]}</h3>${c[1].split('\\n\\n').map(p=>`<p>${p}</p>`).join('')}<button class="chapter-read" data-chapter="${i}">🔊 Read this chapter</button></div></article>`).join('')}</div>`;
    const read=document.querySelector('#museumRead'),stop=document.querySelector('#museumStop'),status=document.querySelector('#museumStatus');
    function museumSpeak(text,button){if(!('speechSynthesis'in window)){status.textContent='Speech is not supported by this browser.';return}speechSynthesis.cancel();document.querySelectorAll('.chapter-read').forEach(b=>b.classList.remove('speaking'));button?.classList.add('speaking');status.textContent='Reading aloud…';const u=new SpeechSynthesisUtterance(text);u.rate=mode==='kids'?.86:.94;u.onend=()=>{button?.classList.remove('speaking');status.textContent='Tour complete.'};speechSynthesis.speak(u)}
    read.onclick=()=>museumSpeak(chapters.map(c=>`${c[0]}. ${c[1]}`).join(' '),read);stop.onclick=()=>{speechSynthesis.cancel();document.querySelectorAll('.speaking').forEach(b=>b.classList.remove('speaking'));status.textContent='Tour stopped.'};document.querySelectorAll('.chapter-read').forEach(b=>b.onclick=()=>museumSpeak(`${chapters[b.dataset.chapter][0]}. ${chapters[b.dataset.chapter][1]}`,b));
  }
})();
